kind: pipeline
type: docker
name: default

steps:
- name: greeting and sleep
  image: golang:1.12
  commands:
  - echo "hello"
  - sleep 20

- name: env and sleep
  image: golang:1.12
  commands:
  - env
  - sleep 20

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general

trigger:
  branch:
    - master
  event:
    - pull_request
