kind: pipeline
type: docker
name: default

steps:
- name: slack-before
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general

- name: docker-build
  image: plugins/docker:18.09
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.io
    repo: kafuhamada/sample
    tags: latest
    debug: true

- name: publish
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: ipu-project/foo/bar
    tags: latest
    debug: true
    json_key:
      from_secret: google_credentials

- name: slack-after
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general

trigger:
  branch:
    - master
  event:
    - pull_request
