kind: pipeline
type: docker
name: default

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general

- name: docker-build
  image: plugins/docker:18.09
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kafuhamada/sample
    tags: latest
    debug: true

trigger:
  branch:
    - master
  event:
    - pull_request
