kind: pipeline
type: docker
name: default

steps:
- name: greeting and sleep
  image: golang:1.12
  commands:
  - echo "hello"
  - sleep 20

- name: env and sleep
  image: golang:1.12
  commands:
  - env
  - sleep 20

trigger:
  branch:
    - develop
  event:
    - pull_request
